//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.MIS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISS01P003 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISS01P003() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.MIS.MISS01P003", typeof(MISS01P003).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept | Reject.
        /// </summary>
        public static string ACCEPT_REJECT {
            get {
                return ResourceManager.GetString("ACCEPT_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreed.
        /// </summary>
        public static string AGREED {
            get {
                return ResourceManager.GetString("AGREED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Date.
        /// </summary>
        public static string CLOSE_DATE {
            get {
                return ResourceManager.GetString("CLOSE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Done.
        /// </summary>
        public static string CONFIRM_FIXED {
            get {
                return ResourceManager.GetString("CONFIRM_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        public static string DEFECT {
            get {
                return ResourceManager.GetString("DEFECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy PD Date.
        /// </summary>
        public static string DEPLOY_PD {
            get {
                return ResourceManager.GetString("DEPLOY_PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy QA Date.
        /// </summary>
        public static string DEPLOY_QA {
            get {
                return ResourceManager.GetString("DEPLOY_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAIL {
            get {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string EFFECTS {
            get {
                return ResourceManager.GetString("EFFECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESSR No.
        /// </summary>
        public static string ESSR_NO {
            get {
                return ResourceManager.GetString("ESSR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string ISE_DATE_OPENING {
            get {
                return ResourceManager.GetString("ISE_DATE_OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue No.
        /// </summary>
        public static string ISE_NO {
            get {
                return ResourceManager.GetString("ISE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue By.
        /// </summary>
        public static string ISSUE_BY {
            get {
                return ResourceManager.GetString("ISSUE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Calculate.
        /// </summary>
        public static string ISSUE_CALCULATE {
            get {
                return ResourceManager.GetString("ISSUE_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string ISSUE_DATE {
            get {
                return ResourceManager.GetString("ISSUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date Period.
        /// </summary>
        public static string ISSUE_DATE_PERIOD {
            get {
                return ResourceManager.GetString("ISSUE_DATE_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Datetime.
        /// </summary>
        public static string ISSUE_DATETIME {
            get {
                return ResourceManager.GetString("ISSUE_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Property.
        /// </summary>
        public static string ISSUE_PROPERTY {
            get {
                return ResourceManager.GetString("ISSUE_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Type.
        /// </summary>
        public static string ISSUE_TYPE {
            get {
                return ResourceManager.GetString("ISSUE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBA.
        /// </summary>
        public static string MAN_PLM_DBA {
            get {
                return ResourceManager.GetString("MAN_PLM_DBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        public static string MAN_PLM_PL {
            get {
                return ResourceManager.GetString("MAN_PLM_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRG.
        /// </summary>
        public static string MAN_PLM_PRG {
            get {
                return ResourceManager.GetString("MAN_PLM_PRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        public static string MAN_PLM_QA {
            get {
                return ResourceManager.GetString("MAN_PLM_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string MAN_PLM_SA {
            get {
                return ResourceManager.GetString("MAN_PLM_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string MODULE {
            get {
                return ResourceManager.GetString("MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        public static string PRG_NAME {
            get {
                return ResourceManager.GetString("PRG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Target.
        /// </summary>
        public static string RESOLUTION_TARGET {
            get {
                return ResourceManager.GetString("RESOLUTION_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response By.
        /// </summary>
        public static string RESPONSE_BY {
            get {
                return ResourceManager.GetString("RESPONSE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Date.
        /// </summary>
        public static string RESPONSE_DATE {
            get {
                return ResourceManager.GetString("RESPONSE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Target.
        /// </summary>
        public static string RESPONSE_TARGET {
            get {
                return ResourceManager.GetString("RESPONSE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Cause.
        /// </summary>
        public static string ROOT_CAUSE {
            get {
                return ResourceManager.GetString("ROOT_CAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string SOLUTION {
            get {
                return ResourceManager.GetString("SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string TARGET_DATE {
            get {
                return ResourceManager.GetString("TARGET_DATE", resourceCulture);
            }
        }
    }
}
